### PR TITLE
Natural events#78

### LINKED ISSUE #86: Broken titles - Natural_Events#78
Change className natTitle

### PR DESCRIPTION
**Pull request by FrederiqueDemas**
Display title + legend
Traduction SeaLakeIce

### CODE REVIEW

**Review by Lora048 — APPROVED** [review]
C'est ok pour moi

**Review by lchastanet — APPROVED** [review]
Everything looks fine

**Comment by FrederiqueDemas** [comment]
Fix broken titles

**Comment by FrederiqueDemas** [comment]
Please for merging into dev, fixing broken titles2.

**Pull request merged**
